### ISSUE TITLE
Add mob variety

### ISSUE THREAD

**Issue by tanyizhe** [tanyizhe/Spellslingers-Orbital#10]

**Comment by tanyizhe** [comment]
Added Ashtoad and bomber

**Comment by tanyizhe** [comment]
Added Blood Mother and Blood Spider

**Comment by alvintfl** [comment]
Added Ice Snail

**Comment by tanyizhe** [comment]
Added ice snail

**Comment by alvintfl** [comment]
Added dust elemental

**Comment by tanyizhe** [comment]
added ash orb

**Comment by tanyizhe** [comment]
Added Ice slime and Ice bat

**Comment by tanyizhe** [comment]
Added Snow thing, rat, giant flybug

**Comment by tanyizhe** [comment]
Added Jungle spirit, hail cloud.
Next is boar and salamander.
