### ISSUE TITLE
Create 3 new skills and 3 enemies

### ISSUE THREAD

**Issue by tanyizhe** [tanyizhe/Spellslingers-Orbital#12]
If time allows, create 3 new enemies and 3 new skills

**Comment by tanyizhe** [comment]
created Ashtoad

**Comment by alvintfl** [comment]
Added preparation skill.

**Comment by tanyizhe** [comment]
Added Blood Mother and Blood Spider enemies.

**Comment by alvintfl** [comment]
Added Frost Shots skill.
