### ISSUE TITLE
Add more skills for build diversity.

### ISSUE THREAD

**Issue by alvintfl** [tanyizhe/Spellslingers-Orbital#6]

**Comment by tanyizhe** [comment]
added Pierce

**Comment by tanyizhe** [comment]
updated entrench and quickstep to give avoidance

**Comment by tanyizhe** [comment]
Added Wind Dancer
Added Wayward Ranger
Added Frost Arrow
Added Weight of the Draw

**Comment by tanyizhe** [comment]
Added 11 warrior and 11 mage skills.
Plan is to create 6 signature skills, perhaps we should make signature skills obtainable every 10 levels.
